FROM python:3.10
USER root

# uvのインストール
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

RUN apt-get update && \
    apt-get -y install --reinstall ca-certificates && \
    apt-get -y install software-properties-common && \
    pip install --upgrade pip && \
    apt-get install -y sudo wget vim curl gawk make gcc git && \
    apt-get install -y graphviz xdg-utils && \
    apt-get install iputils-ping net-tools

# COPY uv.lock pyproject.toml ./
# RUN uv sync --verbose