version: '3'

services:
  workspace:
    container_name: template-environment
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.work
    environment:
      PYTHONPATH: /workspace
      UV_LINK_MODE: copy
    volumes:
      - ..:/workspace
    command: sleep infinity